using System;
using System.Collections.Generic;

namespace NotebookApp
{
    static class DefaultContacts
    {
        public static void AddDefaultContacts(List<Contact> contacts)
        {
            contacts.Add(new Contact() { Lastname = "Рудникова", Firstname = "Берта", Midname = "Мефодиевна", Phonenumber = "3251156535", Country = "Молдавия", Organisation = "Блок", Position = "Кинорежиссер", Birthdate = DateTime.Parse("27.12.1970"), Other = "" });
            contacts.Add(new Contact() { Lastname = "Дрягина", Firstname = "Маргарита", Midname = "Яновна", Phonenumber = "4582211255", Country = "Молдавия", Organisation = "Пром", Position = "Булочник", Birthdate = DateTime.Parse("18.04.1971") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Ягфаров", Firstname = "Моисей", Midname = "Назарович", Phonenumber = "1641994358", Country = "Молдавия", Organisation = "ВидеоПро", Position = "Производственный мастер", Birthdate = DateTime.Parse("08.01.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Беляева", Firstname = "Мария", Midname = "Степановна", Phonenumber = "1976639213", Country = "Молдавия", Organisation = "Мега", Position = "Искусствовед", Birthdate = DateTime.Parse("25.06.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Сарнычев", Firstname = "Дементий", Midname = "Касьянович", Phonenumber = "9500735317", Country = "Молдавия", Organisation = "Фасад", Position = "Винодел", Birthdate = DateTime.Parse("27.10.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Бондарчук", Firstname = "Олег", Midname = "Елизарович", Phonenumber = "6896221182", Country = "Молдавия", Organisation = "Гео", Position = "Психолог", Birthdate = DateTime.Parse("14.11.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Сапогова", Firstname = "Ефросиния", Midname = "Андрияновна", Phonenumber = "5978999288", Country = "Молдавия", Organisation = "Ника", Position = "Дерматовенеролог", Birthdate = DateTime.Parse("18.11.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Висенин", Firstname = "Наум", Midname = "Денисович", Phonenumber = "8962494190", Country = "Молдавия", Organisation = "Агро", Position = "Косметолог", Birthdate = DateTime.Parse("19.11.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Баязов", Firstname = "Самуил", Midname = "Адрианович", Phonenumber = "9631840156", Country = "Македония", Organisation = "Терм", Position = "Зоолог", Birthdate = DateTime.Parse("20.12.1972") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Мышелов", Firstname = "Владилен", Midname = "Иосифович", Phonenumber = "3493421310", Country = "Македония", Organisation = "Монолит", Position = "Прокурор", Birthdate = DateTime.Parse("07.02.1973") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Плаксин", Firstname = "Петр", Midname = "Сигизмундович", Phonenumber = "7277796795", Country = "Македония", Organisation = "Мик", Position = "Отделочник", Birthdate = DateTime.Parse("10.11.1973") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Корнилов", Firstname = "Савелий", Midname = "Пахомович", Phonenumber = "2727742345", Country = "Македония", Organisation = "МонтажФан", Position = "Писатель", Birthdate = DateTime.Parse("18.02.1974") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Елешева", Firstname = "Агафья", Midname = "Владиленовна", Phonenumber = "4837978906", Country = "Македония", Organisation = "Мир", Position = "Логист", Birthdate = DateTime.Parse("23.02.1975") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Гусляков", Firstname = "Якуб", Midname = "Яковович", Phonenumber = "8497177610", Country = "Словакия", Organisation = "Южный", Position = "Технолог", Birthdate = DateTime.Parse("07.03.1975") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Лужкова", Firstname = "Евгения", Midname = "Ираклиевна", Phonenumber = "4728963547", Country = "Словакия", Organisation = "Агро", Position = "Банкир", Birthdate = DateTime.Parse("22.09.1976") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Бранта", Firstname = "Эвелина", Midname = "Данилевна", Phonenumber = "8535436154", Country = "Словакия", Organisation = "МастерФасад", Position = "Фотограф", Birthdate = DateTime.Parse("06.04.1977") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Глушаков", Firstname = "Филипп", Midname = "Демьянович", Phonenumber = "5262933077", Country = "Словакия", Organisation = "Ак", Position = "Стюардесса", Birthdate = DateTime.Parse("05.07.1977") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Бурякова", Firstname = "Алиса", Midname = "Никитевна", Phonenumber = "9675920769", Country = "Словакия", Organisation = "КомЛингва", Position = "Аниматор", Birthdate = DateTime.Parse("29.11.1977") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Чичеринова", Firstname = "Елизавета", Midname = "Брониславовна", Phonenumber = "563179624", Country = "Словакия", Organisation = "НикДизайн", Position = "Маникюрша", Birthdate = DateTime.Parse("24.03.1978") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Болокана", Firstname = "Варвара", Midname = "Всеволодовна", Phonenumber = "9682080859", Country = "Великобритания", Organisation = "Лекс", Position = "Гидролог", Birthdate = DateTime.Parse("21.06.1978") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Кошляка", Firstname = "Анфиса", Midname = "Георгиевна", Phonenumber = "3546612543", Country = "Великобритания", Organisation = "Блок", Position = "Библиограф", Birthdate = DateTime.Parse("07.10.1978") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Кулагина", Firstname = "Пелагея", Midname = "Филипповна", Phonenumber = "628690070", Country = "Великобритания", Organisation = "Пром", Position = "Биолог", Birthdate = DateTime.Parse("27.12.1978") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Яковкин", Firstname = "Всеволод", Midname = "Викентиевич", Phonenumber = "6284270224", Country = "Великобритания", Organisation = "ВидеоПро", Position = "Водолаз", Birthdate = DateTime.Parse("07.05.1979") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Папанов", Firstname = "Петр", Midname = "Куприянович", Phonenumber = "6048203613", Country = "Великобритания", Organisation = "Мега", Position = "Наладчик", Birthdate = DateTime.Parse("28.05.1979") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Толбугин", Firstname = "Ипполит", Midname = "Аникитевич", Phonenumber = "4193291377", Country = "Великобритания", Organisation = "Фасад", Position = "Промоутер", Birthdate = DateTime.Parse("29.07.1979") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Ямилова", Firstname = "Вероника", Midname = "Родионовна", Phonenumber = "6183215692", Country = "Великобритания", Organisation = "Гео", Position = "Программист", Birthdate = DateTime.Parse("04.03.1980") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Прохоров", Firstname = "Андрон", Midname = "Левович", Phonenumber = "3193455889", Country = "Великобритания", Organisation = "Ника", Position = "Web-дизайнер", Birthdate = DateTime.Parse("11.01.1981") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Шашлова", Firstname = "Инга", Midname = "Мироновна", Phonenumber = "7237365021", Country = "Великобритания", Organisation = "Агро", Position = "Разведчик", Birthdate = DateTime.Parse("12.02.1981") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Аводкова", Firstname = "Рената", Midname = "Германовна", Phonenumber = "1552111485", Country = "Великобритания", Organisation = "Терм", Position = "Нанотехнолог", Birthdate = DateTime.Parse("08.03.1982") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Неделяев", Firstname = "Всеволод", Midname = "Измаилович", Phonenumber = "8904493400", Country = "Великобритания", Organisation = "Монолит", Position = "Кондитер", Birthdate = DateTime.Parse("30.07.1982") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Характерова", Firstname = "Арина", Midname = "Юлиевна", Phonenumber = "3800402634", Country = "Великобритания", Organisation = "Мик", Position = "Главный конструктор", Birthdate = DateTime.Parse("03.04.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Гунин", Firstname = "Руслан", Midname = "Юриевич", Phonenumber = "9630879448", Country = "Великобритания", Organisation = "МонтажФан", Position = "Лаборант", Birthdate = DateTime.Parse("15.05.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Мышелов", Firstname = "Агап", Midname = "Давидович", Phonenumber = "5284524698", Country = "Великобритания", Organisation = "Мир", Position = "Уролог", Birthdate = DateTime.Parse("19.05.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Рамазанов", Firstname = "Никон", Midname = "Глебович", Phonenumber = "9890163582", Country = "Великобритания", Organisation = "Южный", Position = "Журналист", Birthdate = DateTime.Parse("24.05.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Базаров", Firstname = "Илья", Midname = "Захарович", Phonenumber = "1309343188", Country = "Великобритания", Organisation = "Агро", Position = "Главный технолог", Birthdate = DateTime.Parse("27.05.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Мадулин", Firstname = "Федор", Midname = "Арсениевич", Phonenumber = "6399868627", Country = "Венгрия", Organisation = "МастерФасад", Position = "Кассир", Birthdate = DateTime.Parse("29.05.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Бурда", Firstname = "Ариадна", Midname = "Михеевна", Phonenumber = "1768116437", Country = "Венгрия", Organisation = "Ак", Position = "Маркетолог", Birthdate = DateTime.Parse("23.11.1983") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Никерова", Firstname = "Инга", Midname = "Борисовна", Phonenumber = "3717135072", Country = "Венгрия", Organisation = "КомЛингва", Position = "Воздухоплаватель", Birthdate = DateTime.Parse("25.05.1984") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Лелуха", Firstname = "Наталья", Midname = "Данилевна", Phonenumber = "7114986738", Country = "Венгрия", Organisation = "НикДизайн", Position = "Товаровед", Birthdate = DateTime.Parse("30.08.1984") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Жичкин", Firstname = "Казимир", Midname = "Миронович", Phonenumber = "9660203086", Country = "Венгрия", Organisation = "Лекс", Position = "Вышивальщица", Birthdate = DateTime.Parse("17.11.1984") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Салькова", Firstname = "Ева", Midname = "Ипполитовна", Phonenumber = "9492090237", Country = "Венгрия", Organisation = "Блок", Position = "Библиотекарь", Birthdate = DateTime.Parse("18.11.1984") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Рассказов", Firstname = "Адам", Midname = "Александрович", Phonenumber = "4143816665", Country = "Венгрия", Organisation = "Пром", Position = "Священнослужитель", Birthdate = DateTime.Parse("25.02.1985") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Елагина", Firstname = "Виктория", Midname = "Данилевна", Phonenumber = "2543941521", Country = "Венгрия", Organisation = "ВидеоПро", Position = "Летчик", Birthdate = DateTime.Parse("18.12.1985") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Зинченко", Firstname = "Николай", Midname = "Адамович", Phonenumber = "1300433278", Country = "Венгрия", Organisation = "Мега", Position = "Экспедитор", Birthdate = DateTime.Parse("05.01.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Шапиро", Firstname = "Светлана", Midname = "Карповна", Phonenumber = "2123789302", Country = "Венгрия", Organisation = "Фасад", Position = "Зубной техник", Birthdate = DateTime.Parse("12.02.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Пелевин", Firstname = "Аскольд", Midname = "Андронович", Phonenumber = "5589642743", Country = "Соединенные Штаты Америки", Organisation = "Гео", Position = "Капитан судна", Birthdate = DateTime.Parse("04.04.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Янчурова", Firstname = "Мария", Midname = "Георгиевна", Phonenumber = "5468886728", Country = "Соединенные Штаты Америки", Organisation = "Ника", Position = "Системный администратор", Birthdate = DateTime.Parse("21.07.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Кобзева", Firstname = "Ярослава", Midname = "Ивановна", Phonenumber = "4273203499", Country = "Соединенные Штаты Америки", Organisation = "Агро", Position = "Судебный пристав", Birthdate = DateTime.Parse("18.10.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Евтушенко", Firstname = "Иван", Midname = "Измаилович", Phonenumber = "7971155571", Country = "Соединенные Штаты Америки", Organisation = "Терм", Position = "Специалист по ВЭД", Birthdate = DateTime.Parse("27.10.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Добронравова", Firstname = "Пелагея", Midname = "Борисовна", Phonenumber = "3091763558", Country = "Соединенные Штаты Америки", Organisation = "Монолит", Position = "Теолог", Birthdate = DateTime.Parse("18.11.1986") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Братцев", Firstname = "Савелий", Midname = "Андреевич", Phonenumber = "3103553450", Country = "Соединенные Штаты Америки", Organisation = "Мик", Position = "Ветеринар", Birthdate = DateTime.Parse("23.02.1987") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Худовекова", Firstname = "Инесса", Midname = "Олеговна", Phonenumber = "2158715918", Country = "Соединенные Штаты Америки", Organisation = "МонтажФан", Position = "Ландшафтный дизайнер", Birthdate = DateTime.Parse("25.04.1987") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Гоминов", Firstname = "Филимон", Midname = "Никонович", Phonenumber = "967323206", Country = "Соединенные Штаты Америки", Organisation = "Мир", Position = "Космонавт", Birthdate = DateTime.Parse("15.06.1987") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Аюшиев", Firstname = "Юлиан", Midname = "Святославович", Phonenumber = "1096342385", Country = "Соединенные Штаты Америки", Organisation = "Южный", Position = "Онколог", Birthdate = DateTime.Parse("13.07.1988") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Луковникова", Firstname = "Дина", Midname = "Игнатиевна", Phonenumber = "4335826727", Country = "Соединенные Штаты Америки", Organisation = "Агро", Position = "Инженер-конструктор", Birthdate = DateTime.Parse("11.09.1988") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Янкин", Firstname = "Агап", Midname = "Мечиславович", Phonenumber = "8501932573", Country = "Россия", Organisation = "МастерФасад", Position = "Массажист", Birthdate = DateTime.Parse("03.11.1988") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Алистратова", Firstname = "Инга", Midname = "Федотовна", Phonenumber = "7091230794", Country = "Россия", Organisation = "Ак", Position = "Полицейский", Birthdate = DateTime.Parse("14.04.1989") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Мельников", Firstname = "Борис", Midname = "Брониславович", Phonenumber = "2995667436", Country = "Россия", Organisation = "КомЛингва", Position = "Психиатр", Birthdate = DateTime.Parse("07.07.1989") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Хребтов", Firstname = "Елисей", Midname = "Никонович", Phonenumber = "4888045402", Country = "Россия", Organisation = "НикДизайн", Position = "Ортопед", Birthdate = DateTime.Parse("11.08.1989") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Грузинский", Firstname = "Артём", Midname = "Егорович", Phonenumber = "464443856", Country = "Россия", Organisation = "Лекс", Position = "Шлифовщик", Birthdate = DateTime.Parse("02.10.1989") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Абрамова", Firstname = "Лиана", Midname = "Леонидовна", Phonenumber = "4251095790", Country = "Россия", Organisation = "Блок", Position = "Режиссер", Birthdate = DateTime.Parse("18.12.1989") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Михалёва", Firstname = "Римма", Midname = "Антониновна", Phonenumber = "8863404745", Country = "Россия", Organisation = "Пром", Position = "Кинооператор", Birthdate = DateTime.Parse("15.05.1990") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Якимовский", Firstname = "Владилен", Midname = "Семенович", Phonenumber = "965350935", Country = "Россия", Organisation = "ВидеоПро", Position = "Дирижер", Birthdate = DateTime.Parse("18.05.1990") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Толбанова", Firstname = "Зинаида", Midname = "Данииловна", Phonenumber = "8628208356", Country = "Россия", Organisation = "Мега", Position = "Эндокринолог (специалист по гормонам)", Birthdate = DateTime.Parse("02.06.1990") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Горюнова", Firstname = "Альбина", Midname = "Николаевна", Phonenumber = "1062436957", Country = "Россия", Organisation = "Фасад", Position = "Реаниматолог", Birthdate = DateTime.Parse("29.07.1990") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Игошин", Firstname = "Вадим", Midname = "Еремеевич", Phonenumber = "1226220748", Country = "Россия", Organisation = "Гео", Position = "Менеджер по продажам", Birthdate = DateTime.Parse("17.08.1990") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Цельнера", Firstname = "Милена", Midname = "Потаповна", Phonenumber = "7777512234", Country = "Россия", Organisation = "Ника", Position = "Кодер", Birthdate = DateTime.Parse("13.09.1990") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Чайка", Firstname = "Инга", Midname = "Данилевна", Phonenumber = "674369150", Country = "Россия", Organisation = "Агро", Position = "Администратор сайта", Birthdate = DateTime.Parse("07.01.1991") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Якунчиков", Firstname = "Серафим", Midname = "Иосифович", Phonenumber = "7769743691", Country = "Россия", Organisation = "Терм", Position = "Животновод", Birthdate = DateTime.Parse("16.02.1991") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Никерхоева", Firstname = "Роза", Midname = "Ростиславовна", Phonenumber = "7898121641", Country = "Россия", Organisation = "Монолит", Position = "Гинеколог", Birthdate = DateTime.Parse("08.03.1991") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Усова", Firstname = "Рада", Midname = "Леонидовна", Phonenumber = "1568573511", Country = "Россия", Organisation = "Мик", Position = "HTML-верстальщик", Birthdate = DateTime.Parse("11.05.1991") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Юшаков", Firstname = "Максимильян", Midname = "Александрович", Phonenumber = "8003462699", Country = "Россия", Organisation = "МонтажФан", Position = "Мусорщик", Birthdate = DateTime.Parse("14.07.1991") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Ябров", Firstname = "Артур", Midname = "Давидович", Phonenumber = "9751916148", Country = "Россия", Organisation = "Мир", Position = "Маляр", Birthdate = DateTime.Parse("22.03.1992") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Мозговой", Firstname = "Герасим", Midname = "Святославович", Phonenumber = "1629081119", Country = "Россия", Organisation = "Южный", Position = "Официант", Birthdate = DateTime.Parse("22.09.1992") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Жолдин", Firstname = "Аскольд", Midname = "Мартьянович", Phonenumber = "1277437487", Country = "Россия", Organisation = "Агро", Position = "Страховой агент", Birthdate = DateTime.Parse("26.12.1992") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Куклачёв", Firstname = "Максимильян", Midname = "Ермолаевич", Phonenumber = "3815430301", Country = "Россия", Organisation = "МастерФасад", Position = "Фальцовщик", Birthdate = DateTime.Parse("26.02.1993") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Кондра", Firstname = "Ефросинья", Midname = "Степановна", Phonenumber = "3102223145", Country = "Россия", Organisation = "Ак", Position = "Продавец", Birthdate = DateTime.Parse("06.04.1993") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Умников", Firstname = "Платон", Midname = "Макарович", Phonenumber = "2396134868", Country = "Россия", Organisation = "КомЛингва", Position = "Художник по костюму", Birthdate = DateTime.Parse("14.06.1993") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Туржанский", Firstname = "Максимильян", Midname = "Карлович", Phonenumber = "8421452656", Country = "Россия", Organisation = "НикДизайн", Position = "Секретарь-стенографистка", Birthdate = DateTime.Parse("18.08.1994") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Порошина", Firstname = "Ефросинья", Midname = "Ивановна", Phonenumber = "5807222864", Country = "Россия", Organisation = "Лекс", Position = "Вирусолог", Birthdate = DateTime.Parse("26.09.1994") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Николаенко", Firstname = "Ника", Midname = "Георгиевна", Phonenumber = "5129616494", Country = "Россия", Organisation = "Блок", Position = "Консультант телефона доверия", Birthdate = DateTime.Parse("10.01.1995") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Смолянинова", Firstname = "Зоя", Midname = "Антониновна", Phonenumber = "1637902587", Country = "Россия", Organisation = "Пром", Position = "Менеджер по PR", Birthdate = DateTime.Parse("19.04.1995") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Яблочкина", Firstname = "Зинаида", Midname = "Никитевна", Phonenumber = "8460757262", Country = "Россия", Organisation = "ВидеоПро", Position = "Генный инженер", Birthdate = DateTime.Parse("10.10.1995") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Фастера", Firstname = "Фаина", Midname = "Вячеславовна", Phonenumber = "9291840231", Country = "Россия", Organisation = "Мега", Position = "Горняк", Birthdate = DateTime.Parse("18.10.1995") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Перминов", Firstname = "Илья", Midname = "Дмитриевич", Phonenumber = "7888136885", Country = "Россия", Organisation = "Фасад", Position = "Рихтовщик", Birthdate = DateTime.Parse("24.12.1995") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Кылымныка", Firstname = "Тамара", Midname = "Павеловна", Phonenumber = "5600326666", Country = "Россия", Organisation = "Гео", Position = "Администратор гостиницы", Birthdate = DateTime.Parse("13.02.1996") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Старкова", Firstname = "Светлана", Midname = "Игоревна", Phonenumber = "5770704991", Country = "Россия", Organisation = "Ника", Position = "Изобретатель", Birthdate = DateTime.Parse("04.05.1996") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Блокова", Firstname = "Оксана", Midname = "Несторовна", Phonenumber = "8091689214", Country = "Россия", Organisation = "Агро", Position = "Ремонтник", Birthdate = DateTime.Parse("10.10.1996") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Аношкин", Firstname = "Трофим", Midname = "Карлович", Phonenumber = "2524181876", Country = "Россия", Organisation = "Терм", Position = "Трейдер", Birthdate = DateTime.Parse("06.11.1996") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Салагин", Firstname = "Лев", Midname = "Тихонович", Phonenumber = "5735125313", Country = "Россия", Organisation = "Монолит", Position = "Дизайнер рекламы", Birthdate = DateTime.Parse("16.09.1997") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Новомейский", Firstname = "Лев", Midname = "Александрович", Phonenumber = "599520003", Country = "Россия", Organisation = "Мик", Position = "Преподаватель", Birthdate = DateTime.Parse("12.10.1998") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Шубина", Firstname = "Римма", Midname = "Афанасиевна", Phonenumber = "2871958613", Country = "Россия", Organisation = "МонтажФан", Position = "Востоковед", Birthdate = DateTime.Parse("20.02.1999") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Беломестов", Firstname = "Кузьма", Midname = "Андреевич", Phonenumber = "4947578919", Country = "Россия", Organisation = "Мир", Position = "Кардиолог", Birthdate = DateTime.Parse("07.04.1999") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Ильин", Firstname = "Виталий", Midname = "Панкратиевич", Phonenumber = "1813913276", Country = "Россия", Organisation = "Южный", Position = "Балетмейстер", Birthdate = DateTime.Parse("31.05.1999") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Жжёнова", Firstname = "Ирина", Midname = "Игнатиевна", Phonenumber = "5700661096", Country = "Россия", Organisation = "Агро", Position = "Облицовщик", Birthdate = DateTime.Parse("18.08.1999") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Сафонов", Firstname = "Агафон", Midname = "Всеволодович", Phonenumber = "4352243104", Country = "Россия", Organisation = "МастерФасад", Position = "Биоинженер", Birthdate = DateTime.Parse("29.03.2000") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Любова", Firstname = "Эльвира", Midname = "Мефодиевна", Phonenumber = "1793120736", Country = "Россия", Organisation = "Ак", Position = "Мультипликатор", Birthdate = DateTime.Parse("26.04.2000") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Обухов", Firstname = "Онуфрий", Midname = "Венедиктович", Phonenumber = "3729928523", Country = "Россия", Organisation = "КомЛингва", Position = "Стилист", Birthdate = DateTime.Parse("06.12.2000") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Боголюбов", Firstname = "Эрнест", Midname = "Трофимович", Phonenumber = "7502822224", Country = "Россия", Organisation = "НикДизайн", Position = "Грузчик", Birthdate = DateTime.Parse("04.01.2001") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Коржуков", Firstname = "Ростислав", Midname = "Тихонович", Phonenumber = "2714898451", Country = "Россия", Organisation = "Лекс", Position = "Кинодраматург", Birthdate = DateTime.Parse("15.03.2001") , Other = "" });
            contacts.Add(new Contact() { Lastname = "Аникин", Firstname = "Даниил", Midname = "Александрович", Phonenumber = "89816877871", Country = "Россия", Organisation = "Технолинк", Position = "Инженер АСУП", Birthdate = DateTime.Parse("25.12.1997") , Other = "" });

        }
    }
}
